BEGIN;

CREATE TABLE IF NOT EXISTS emergency_contacts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premise_id      INTEGER NOT NULL
                    REFERENCES premises(id) ON DELETE CASCADE,
    contact_name    VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(20) NOT NULL,
    relationship    VARCHAR(100),
    priority        SMALLINT NOT NULL DEFAULT 1,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_emergency_contacts_premise_phone
        UNIQUE (premise_id, phone_number),
    CONSTRAINT ck_emergency_contacts_priority CHECK (
        priority BETWEEN 1 AND 100
    )
);

CREATE INDEX IF NOT EXISTS ix_emergency_contacts_premise_priority
    ON emergency_contacts(premise_id, priority);

COMMIT;
