BEGIN;

CREATE TABLE premises (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    type            VARCHAR(100),
    address         TEXT
);

CREATE TABLE premise_settings (
    premise_id              INTEGER PRIMARY KEY
                            REFERENCES premises(id) ON DELETE CASCADE,
    auto_delete_images      BOOLEAN NOT NULL DEFAULT TRUE,
    image_retention_days    INTEGER NOT NULL DEFAULT 30,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_premise_settings_retention CHECK (
        image_retention_days BETWEEN 1 AND 3650
    )
);

CREATE TABLE profiles (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premise_id          INTEGER REFERENCES premises(id) ON DELETE SET NULL,
    username            VARCHAR(255) NOT NULL,
    email               VARCHAR(255) NOT NULL UNIQUE,
    phone_number        VARCHAR(20) UNIQUE,
    group_type          VARCHAR(100) NOT NULL,
    hash_password       TEXT NOT NULL,
    face_signature      TEXT,
    profile_image_path  TEXT,
    last_seen           TIMESTAMPTZ,
    is_blacklisted      BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_profiles_group_type CHECK (
        group_type IN ('owner', 'manager', 'normal_user')
    )
);

CREATE INDEX ix_profiles_premise_id ON profiles(premise_id);

CREATE TABLE emergency_contacts (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premise_id      INTEGER NOT NULL
                    REFERENCES premises(id) ON DELETE CASCADE,
    contact_name    VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(20) NOT NULL,
    relationship    VARCHAR(100),
    priority        SMALLINT NOT NULL DEFAULT 1,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_emergency_contacts_premise_phone
        UNIQUE (premise_id, phone_number),
    CONSTRAINT ck_emergency_contacts_priority CHECK (
        priority BETWEEN 1 AND 100
    )
);

CREATE INDEX ix_emergency_contacts_premise_priority
    ON emergency_contacts(premise_id, priority);

CREATE TABLE devices (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premise_id          INTEGER NOT NULL REFERENCES premises(id) ON DELETE CASCADE,
    device_name         VARCHAR(255) NOT NULL,
    device_type         VARCHAR(50) NOT NULL,
    location            VARCHAR(255),
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    connection_status   VARCHAR(20) NOT NULL DEFAULT 'offline',
    last_heartbeat      TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_devices_premise_name UNIQUE (premise_id, device_name),
    CONSTRAINT ck_devices_type CHECK (device_type IN ('camera', 'sensor')),
    CONSTRAINT ck_devices_connection_status CHECK (
        connection_status IN ('online', 'offline', 'connecting', 'error')
    )
);

CREATE INDEX ix_devices_premise_id ON devices(premise_id);
CREATE INDEX ix_devices_type ON devices(device_type);

-- Camera and sensor are disjoint subtypes of Device. Their device_id is both
-- the subtype primary key and a foreign key to the supertype.
CREATE TABLE cameras (
    device_id              INTEGER PRIMARY KEY
                           REFERENCES devices(id) ON DELETE CASCADE,
    stream_url             TEXT NOT NULL,
    username               VARCHAR(255),
    encrypted_password     TEXT,
    stream_protocol        VARCHAR(20) NOT NULL DEFAULT 'rtsp',
    confidence_threshold   NUMERIC(4,3) NOT NULL DEFAULT 0.700,
    snapshot_enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    detection_enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_cameras_stream_protocol CHECK (
        stream_protocol IN ('rtsp', 'http', 'https')
    ),
    CONSTRAINT ck_cameras_confidence_threshold CHECK (
        confidence_threshold BETWEEN 0 AND 1
    )
);

-- Defines the AI capabilities supported by the application. A camera can
-- enable or disable each capability independently through camera_ai_features.
CREATE TABLE ai_detection_types (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    description     TEXT
);

CREATE TABLE camera_ai_features (
    camera_id              INTEGER NOT NULL
                           REFERENCES cameras(device_id) ON DELETE CASCADE,
    ai_detection_type_id   INTEGER NOT NULL
                           REFERENCES ai_detection_types(id) ON DELETE RESTRICT,
    enabled                BOOLEAN NOT NULL DEFAULT TRUE,
    confidence_threshold   NUMERIC(4,3) NOT NULL DEFAULT 0.700,
    PRIMARY KEY (camera_id, ai_detection_type_id),
    CONSTRAINT ck_camera_ai_features_confidence CHECK (
        confidence_threshold BETWEEN 0 AND 1
    )
);

CREATE TABLE sensors (
    device_id           INTEGER PRIMARY KEY
                        REFERENCES devices(id) ON DELETE CASCADE,
    sensor_type         VARCHAR(100) NOT NULL,
    sampling_interval   INTEGER,
    CONSTRAINT ck_sensors_sampling_interval CHECK (
        sampling_interval IS NULL OR sampling_interval > 0
    )
);

CREATE TABLE measurement_types (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    default_unit    VARCHAR(30) NOT NULL
);

CREATE TABLE sensor_capabilities (
    sensor_id              INTEGER NOT NULL
                           REFERENCES sensors(device_id) ON DELETE CASCADE,
    measurement_type_id    INTEGER NOT NULL
                           REFERENCES measurement_types(id) ON DELETE RESTRICT,
    minimum_value          NUMERIC(12,3),
    maximum_value          NUMERIC(12,3),
    warning_threshold      NUMERIC(12,3),
    critical_threshold     NUMERIC(12,3),
    PRIMARY KEY (sensor_id, measurement_type_id),
    CONSTRAINT ck_sensor_capability_range CHECK (
        minimum_value IS NULL OR maximum_value IS NULL
        OR minimum_value <= maximum_value
    )
);

CREATE TABLE sensor_readings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id       INTEGER NOT NULL REFERENCES sensors(device_id) ON DELETE CASCADE,
    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_sensor_readings_sensor_time
    ON sensor_readings(sensor_id, recorded_at DESC);

CREATE TABLE reading_values (
    reading_id              BIGINT NOT NULL
                            REFERENCES sensor_readings(id) ON DELETE CASCADE,
    measurement_type_id     INTEGER NOT NULL
                            REFERENCES measurement_types(id) ON DELETE RESTRICT,
    value                   NUMERIC(12,3) NOT NULL,
    PRIMARY KEY (reading_id, measurement_type_id)
);

CREATE INDEX ix_reading_values_measurement_type
    ON reading_values(measurement_type_id);

CREATE TABLE ai_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    premise_id          INTEGER NOT NULL REFERENCES premises(id) ON DELETE CASCADE,
    source_device_id    INTEGER REFERENCES devices(id) ON DELETE SET NULL,
    sensor_reading_id   BIGINT REFERENCES sensor_readings(id) ON DELETE SET NULL,
    profile_id          INTEGER REFERENCES profiles(id) ON DELETE SET NULL,
    event_type          VARCHAR(100) NOT NULL,
    severity            VARCHAR(20) NOT NULL DEFAULT 'medium',
    confidence_score    NUMERIC(4,3),
    image_path          TEXT,
    is_acknowledged     BOOLEAN NOT NULL DEFAULT FALSE,
    timestamp           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ai_events_severity CHECK (
        severity IN ('low', 'medium', 'high', 'critical')
    ),
    CONSTRAINT ck_ai_events_confidence CHECK (
        confidence_score IS NULL
        OR confidence_score BETWEEN 0 AND 1
    )
);

CREATE INDEX ix_ai_events_premise_time
    ON ai_events(premise_id, timestamp DESC);
CREATE INDEX ix_ai_events_source_device
    ON ai_events(source_device_id);
CREATE INDEX ix_ai_events_sensor_reading
    ON ai_events(sensor_reading_id);
CREATE INDEX ix_ai_events_profile
    ON ai_events(profile_id);

-- Seed the measurement types currently supported by the application.
INSERT INTO measurement_types (name, default_unit)
VALUES
    ('temperature', '°C'),
    ('humidity', '%'),
    ('gas_level', 'ppm');

INSERT INTO ai_detection_types (name, description)
VALUES
    ('person_detection', 'Detects people in the camera feed'),
    ('face_recognition', 'Recognizes registered and unknown faces'),
    ('behavioral_anomaly', 'Detects unusual or suspicious behaviour');

COMMIT;
